# -*- coding: utf-8 -*-
"""model_testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k19oyFiqovetsfJoVylHdtmHaLs1fbEz
"""

#Импорт необходимых модулей
import pandas as pd
import pickle
from sklearn.metrics import accuracy_score

# Загрузка тренировочной модели
with open('model_logreg_train.pkl', 'rb') as f:
    model = pickle.load(f)

# Загрузка тестовых данных из test_Data_sizes.csv
test_data = pd.read_csv('test/test_Data_sizes.csv')

# Выделение зависимой (целевой) переменной y и независимой переменной-предиктора X
X_test = test_data[['bust', 'waist', 'hips']]
y_test = test_data['Class']

# Выгрузка предобработанных данных
scaler = pickle.load(open('data_preprocessing.pkl', 'rb'))['scaler']
X_test_scaled = scaler.transform(X_test)

#Делаем предсказания на тестовых данных
y_pred = model.predict(X_test_scaled)

# Оценим качество предсказания
test_accuracy = accuracy_score(y_test, y_pred)

print(f"Качество предсказания на тестовых данных аccuracy: {test_accuracy}")