# -*- coding: utf-8 -*-
"""model_preparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10y8Dz5nGeSNvgOD3bcFIy4HUzpqMXNaS
"""

#Импорт необходимых модулей
import pandas as pd
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Считывание данных в датафрейм
data_preprocessing = pd.read_pickle('data_preprocessing.pkl')

X_train = data_preprocessing['X_train']
y_train = data_preprocessing['y_train']

# Обучение модели Логистической регресии
model = LogisticRegression()
model.fit(X_train, y_train)

# Сохраняем тренировочную модель
filename = 'model_logreg_train.pkl'
with open(filename, 'wb') as f:
    pickle.dump(model, f)

print(f"Обучение модели на тренирововчных данных выполнено. Модель успешно сохранена в {filename}")

#Делаем предсказания
y_pred = model.predict(X_train)
accuracy = accuracy_score(y_train, y_pred)
print(accuracy)
print(classification_report(y_train, y_pred))